spring:
  application:
    name: punto-de-apoyo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:punto-de-apoyo}
      secret: ${JWT_SECRET}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}
  storage:
    upload-dir: ${APP_UPLOAD_DIR:uploads}
